AllCops:
    NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/PerceivedComplexity:
  Exclude:
    - 'bin/bundle'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'bin/bundle'

Metrics/MethodLength:
  Exclude:
    - 'bin/bundle'

Layout/LineLength:
  Exclude:
    - 'bin/bundle'
