default: &default
  adapter: postgresql
  host: db
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: garbage_tracker_development
  username: postgres
  password: password

test:
  <<: *default
  adapter: sqlite3
  database: db/garbage_tracker_test.sqlite3

production:
  <<: *default
  database: garbage_tracker_production
  username: garbage_tracker
  password: <%= ENV['GARBAGE_TRACKER_DATABASE_PASSWORD'] %>
