name: CI

on: [push]

jobs: 
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.3
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Build and check for rubocop issues
      run: |
        bundle exec rubocop
  bundle-outdated:
    name: Bundle oudated
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.3
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Build and check outdated gems
      continue-on-error: true
      run: |
        bundle outdated
  rspec:
    name: rspec
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.3
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Build and test
      continue-on-error: true
      run: |
        bundle exec rspec spec
